(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



myArg[a_,b_,r_]:= Mod[Arg[N[a.b/(Norm[a]Norm[b])+I*Cross[a,b].r/(Norm[a]Norm[b])]],2Pi]


ArgList[neighbors_]:=
Map[myArg[neighbors[[2,1]],#,neighbors[[1]]]&,Drop[Map[#-neighbors[[2,1]]&,neighbors[[2]]],1]]



